#!/bin/sh

# First we append the saved layout of workspace N to workspace M
i3-msg "workspace 4: Py; append_layout ~/.config/i3/layouts/workspaces/ws4.json"

# And finally we fill the containers with the programs they had
(~/app_images/pycharm/bin/pycharm.sh &)