#!/bin/sh

# First we append the saved layout of workspace N to workspace M
i3-msg "workspace 1: System; append_layout ~/.config/i3/layouts/workspaces/ws1.json"

# And finally we fill the containers with the programs they had
(alacritty &)
(sleep 1 &)
(alacritty &)
(sleep 1 &)
(alacritty &)
(sleep 1 &)
(alacritty &)
(sleep 1 &)
(alacritty &)